language: java
sudo: false

jdk:
  - openjdk8

env: 
  # Give Maven 1GB of memory to work with
  - MAVEN_OPTS=-Xmx2048M

# Skip install stage, as we'll do it below
install: "echo 'Skipping install stage, dependencies will be downloaded during build and test stages.'"

# Two stage Build and Test
# 1. Install and assembly & Unit Test APIs
script:
  # 1. [Install & Unit Test] Check source code licenses and run source code Unit Tests
  #        license:check => Validate all source code license headers
  #        -Dmaven.test.skip=false => Enable DSpace Unit Tests
  #        -DskipITs=false         => Enable DSpace Integration Tests
  #        -P !assembly            => Skip normal assembly (as it can be memory intensive)
  #        -B => Maven batch/non-interactive mode (recommended for CI)
  #        -V => Display Maven version info before build
  #        -Dsurefire.rerunFailingTestsCount=2 => try again for flakey tests, and keep track of/report on number of retries
  - "mvn clean package license:check -Dmaven.test.skip=true -DskipITs=true -P !assembly -B -V"  
